### ISSUE TITLE
Implement the dark mode.

### ISSUE THREAD

**Issue by Suraj-kumar00** [Suraj-kumar00/Flash-Fathom-AI#1]
The toggle has already been added with Shadcn UI.
- Add dark mode functionality which works on all pages.

https://github.com/user-attachments/assets/190b8ec8-eadd-4994-9fe0-8f65e738a670

**Comment by kiinshuk** [comment]
Hi @Suraj-kumar00 , I'd like to help with this enhancement. Could you please assign it to me?

**Comment by Suraj-kumar00** [comment]
Hi @kiinshuk, thanks for taking time to work on this issue.
Yeah you can work on this issue. While creating pull request please upload preview and also let me know how you going to improve.

**Comment by kiinshuk** [comment]
Hi, I'm having trouble setting up the project due to too many complications. I'm sorry for any inconvenience caused, but could you please unassign me from the issue?

**Comment by Suraj-kumar00** [comment]
Okay, but what happened @kiinshuk ?

**Comment by AnushkaChouhan25** [comment]
.take

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, Please update the progress on the issue. 
Otherwise I have to give a chance to other contributors as well. Hope you understand.

**Comment by AnushkaChouhan25** [comment]
Hello @Suraj-kumar00, Yeah, I understand. I will surely let you know tomorrow. Otherwise, you can assign to others.

**Comment by AnushkaChouhan25** [comment]
Hi @Suraj-kumar00, I hope you are doing well. I’m facing some problems in the following files:
![image](https://github.com/user-attachments/assets/281c560f-3d7a-493f-91f8-44bd2bc23dde)

Despite my efforts, I wasn’t able to resolve the issue. And, whenever I commit my changes, these changes automatically appear in the pull request, and I’m concerned that this might cause further problems.
I’m really sorry for the inconvenience. You can unassign me, and I hope someone else can solve this issue. 
Thank you!

**Comment by Suraj-kumar00** [comment]
> Hi @Suraj-kumar00, I hope you are doing well. I’m facing some problems in the following files: ![image](https://private-user-images.githubusercontent.com/157525924/378070850-281c560f-3d7a-493f-91f8-44bd2bc23dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU2MDcsIm5iZiI6MTcyOTMzNTMwNywicGF0aCI6Ii8xNTc1MjU5MjQvMzc4MDcwODUwLTI4MWM1NjBmLTNkN2EtNDkzZi05MWY4LTQ0YmQyYmMyM2RkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmZmYWI3NDQyMmE2ODcyNDdmZGFkMTdmNmM1NGI0YjA3NjI5NjIxYjlkMmMyMDc3YmU5MzUxMGFmODIwODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PAvXDL6hJMDWt2EXUNz5jKpekQeFgfaxFmkbIaSe590)
> 
> Despite my efforts, I wasn’t able to resolve the issue. And, whenever I commit my changes, these changes automatically appear in the pull request, and I’m concerned that this might cause further problems. I’m really sorry for the inconvenience. You can unassign me, and I hope someone else can solve this issue. Thank you!

If you are facing any problem you can ask for help @AnushkaChouhan25, that's what open-source community is about!
But anyways you wish to not to work on this issue I'll assign it to other contributor.
