### ISSUE TITLE
Missing docker-compose.yml File for Backend Setup

### ISSUE THREAD

**Issue by Sachin2815** [Suraj-kumar00/Flash-Fathom-AI#10]
Hey! @Suraj-kumar00  

I noticed that the repository does not contain a `docker-compose.yml` file, which is essential for streamlining the setup of the backend services, particularly for the PostgreSQL database integration.

I have extensive experience in setting up Docker environments for both local development and production use. I've worked on several projects where `docker-compose` played a crucial role in streamlining the development process, and I am confident that I can deliver a high-quality solution for this repository.

The addition of a `docker-compose.yml` file would greatly improve the development and deployment process by enabling easier orchestration of the backend services using Docker. It can help set up both the Axum-based Rust backend and the PostgreSQL database seamlessly.

## Proposed Solution

I would like to contribute by adding a `docker-compose.yml` file that:

- Defines services for the backend and PostgreSQL.
- Configures networking to allow smooth communication between the backend and the database.
- Includes relevant environment variables for database setup (e.g., username, password, database name).

This will allow contributors and developers to quickly spin up the backend environment using Docker, enhancing productivity and minimizing setup errors.

Please let me know if this sounds like a good enhancement, and I'd be happy to get started! 😊

Thank you for your consideration!

**Comment by Sachin2815** [comment]
Hi @Suraj-kumar00 , thank you for your response and for the clarification!

I understand that the current setup uses Firebase Firestore, but if you're open to shifting the backend and database to Supabase + PostgreSQL + Prisma ORM, I'd be happy to assist with that transition. Below is a high-level overview of how I would approach this migration:

## Proposed Solution

1. **Backend Setup**:
   - I would use **Supabase** as a backend service, which provides a PostgreSQL database and real-time functionalities.
   - Prisma ORM would be used for database management, providing an abstraction layer to interact with PostgreSQL, making database operations simpler and type-safe.

2. **Database Migration**:
   - I will assist in migrating data from Firestore to PostgreSQL. We can export Firestore collections and write a migration script to insert them into the corresponding tables in PostgreSQL.

3. **Docker Setup**:
   - I will create a `docker-compose.yml` file to define services for both the Supabase (PostgreSQL) database and the backend.
   - This setup will allow seamless communication between the backend and PostgreSQL, along with relevant environment variables for database configuration (username, password, database name).

4. **Prisma ORM Integration**:
   - I will configure **Prisma** for database schema generation and migrations, ensuring that the models match the Firestore data structure.
   - Prisma’s migration feature will handle any future database updates efficiently.

5. **Benefits of Supabase + PostgreSQL**:
   - **Supabase** offers a robust, scalable solution, and being powered by PostgreSQL makes it an ideal choice for structured data.
   - Using **Prisma ORM** will simplify database queries and interactions, improve code readability, and enhance productivity.

### How I Will Do This:
- Create a migration plan to safely transfer data from Firestore to PostgreSQL.
- Set up Supabase as the new backend database service, with the necessary configurations.
- Integrate Prisma ORM for data management and schema generation.
- Add a `docker-compose.yml` file to orchestrate the backend and database services using Docker.

If this approach works for you, I can start working on a detailed plan and the implementation. Let me know if you would like to discuss this further!

Thank you again for your time and consideration! 😊

**Comment by Suraj-kumar00** [comment]
Hi @Sachin2815, Sound good to me.
Let's do!

**Comment by Suraj-kumar00** [comment]
> Hi @Suraj-kumar00 , thank you for your response and for the clarification!
> 
> I understand that the current setup uses Firebase Firestore, but if you're open to shifting the backend and database to Supabase + PostgreSQL + Prisma ORM, I'd be happy to assist with that transition. Below is a high-level overview of how I would approach this migration:
> 
> ## Proposed Solution
> 1. **Backend Setup**:
>    
>    * I would use **Supabase** as a backend service, which provides a PostgreSQL database and real-time functionalities.
>    * Prisma ORM would be used for database management, providing an abstraction layer to interact with PostgreSQL, making database operations simpler and type-safe.
> 2. **Database Migration**:
>    
>    * I will assist in migrating data from Firestore to PostgreSQL. We can export Firestore collections and write a migration script to insert them into the corresponding tables in PostgreSQL.
> 3. **Docker Setup**:
>    
>    * I will create a `docker-compose.yml` file to define services for both the Supabase (PostgreSQL) database and the backend.
>    * This setup will allow seamless communication between the backend and PostgreSQL, along with relevant environment variables for database configuration (username, password, database name).
> 4. **Prisma ORM Integration**:
>    
>    * I will configure **Prisma** for database schema generation and migrations, ensuring that the models match the Firestore data structure.
>    * Prisma’s migration feature will handle any future database updates efficiently.
> 5. **Benefits of Supabase + PostgreSQL**:
>    
>    * **Supabase** offers a robust, scalable solution, and being powered by PostgreSQL makes it an ideal choice for structured data.
>    * Using **Prisma ORM** will simplify database queries and interactions, improve code readability, and enhance productivity.
> 
> ### How I Will Do This:
> * Create a migration plan to safely transfer data from Firestore to PostgreSQL.
> * Set up Supabase as the new backend database service, with the necessary configurations.
> * Integrate Prisma ORM for data management and schema generation.
> * Add a `docker-compose.yml` file to orchestrate the backend and database services using Docker.
> 
> If this approach works for you, I can start working on a detailed plan and the implementation. Let me know if you would like to discuss this further!
> 
> Thank you again for your time and consideration! 😊

After completing the issue, help me to restructure the architectural workflow of the project.
