### ISSUE TITLE
Sign In Redirect Failed

### ISSUE THREAD

**Issue by Ahsankhalid618** [Suraj-kumar00/Flash-Fathom-AI#14]
**Describe the bug**
When the user signs in or signs up, it doesn't redirect the user to the website or even doesn't register the user.

**To Reproduce**
1. Go to SignIn/SignUp
2. Click on Login/SignUp
3. It will take you to clerk signup/sign-in.
4. Redirect Failed.

**Expected behavior**
The user should sign up successfully and be redirected to the website.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b695ff6-b412-45f6-a82d-7b397991ec66)

Assign me this issue.

**Comment by Suraj-kumar00** [comment]
Hi @Ahsankhalid618, how have you been?
Actually it's working fine on the deployement, could you please share the actual error you are facing?

**Comment by Ahsankhalid618** [comment]
Yeah it's working now, Did'nt work the first time I tried but now working fine.
