### ISSUE TITLE
Create a demo video of the project.

### ISSUE THREAD

**Issue by Suraj-kumar00** [Suraj-kumar00/Flash-Fathom-AI#15]
Create complete demo video of how the project works:
- Head over to the landing page.
- Sign-in with gooogle.
- Generate flashcard of any teach topics like `DevOps` `Cloud` `Development` etc...

After the video completes Update it to the `README` file  Below the description and above Build with section like in between them.

The video only include the entering on the landing page and generating and saving the flascard. no more no less.

**Comment by Shivansh-22866** [comment]
@Suraj-kumar00 assign me the issue

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 assign me the issue

It's yours @Shivansh-22866.
Do remember you have three days to complete this issue.

And If you like the project do give it a star :star2:
