### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Suraj-kumar00/Flash-Fathom-AI#20]
I want to add a page to showcase all the contributors of this website. @Suraj-kumar00 can you assign me this issue,

**Comment by Suraj-kumar00** [comment]
@T-Rahul-prabhu-38 I think there is not need of doing that instead of this you can add all contributors github photo and usernames(with link) and if its possible like automatically update all the future contributors to the readme file? If you can do this let me know!

**Comment by T-Rahul-prabhu-38** [comment]
yes

**Comment by T-Rahul-prabhu-38** [comment]
thts what i was actually proposing.

**Comment by T-Rahul-prabhu-38** [comment]
<img width="1457" alt="Screenshot 2024-10-18 at 4 44 57 PM" src="https://github.com/user-attachments/assets/5bd4bcd5-ece8-4510-9d47-dcfa178bcbbf">
it will be like this
<img width="1326" alt="Screenshot 2024-10-18 at 4 45 03 PM" src="https://github.com/user-attachments/assets/f2616560-acd5-4941-ba89-5ddcfa17cb89">

**Comment by T-Rahul-prabhu-38** [comment]
i can add it to readme file aswell.

**Comment by Suraj-kumar00** [comment]
> Hey Rahul that's great! let's go but I think for now these should be in the README file only.

Hey don't forget to give the repo a star :star2:

**Comment by T-Rahul-prabhu-38** [comment]
ok sure 
ill do that

**Comment by Suraj-kumar00** [comment]
Hi @T-Rahul-prabhu-38, you can see I have merged your pr and you are showing the contributor on the github's contributors section but not in the REAMDE. It's not updating automatically?

**Comment by T-Rahul-prabhu-38** [comment]
it might take time

**Comment by T-Rahul-prabhu-38** [comment]
like its all API calls right , it will take sometime.

**Comment by T-Rahul-prabhu-38** [comment]
i have 2 more PR to make , lets see by then

**Comment by Suraj-kumar00** [comment]
> i have 2 more PR to make , lets see by then

Let's see because previous contributors update this till then it's not working, hope you updation will work
