### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by Suraj-kumar00** [Suraj-kumar00/Flash-Fathom-AI#28]
- Create the PR template, like whenever contributor raises the PR the PR templates should appear to contributor.
- PR template should include the important heading should contributor should fill according to the issue the contributor have worked on.

Ask if you need any details.

**Comment by milansamuel609** [comment]
Can you assign me this one? Just tell for what you have to create the template for like documentation, any update in code or other thing.

**Comment by Suraj-kumar00** [comment]
Hey @milansamuel609, thanks for your contribution.
I mean you gave take references of common questions like what issue is solve like the issue number so that in the issue PR will automatically link, and other question like what changes you have make any preview like screenshot or viedeo! I think you got the idea but still take the reference from open source community see how other open source project have their PR template choose good and add it to this project.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609, thanks for your contribution. I mean you gave take references of common questions like what issue is solve like the issue number so that in the issue PR will automatically link, and other question like what changes you have make any preview like screenshot or viedeo! I think you got the idea but still take the reference from open source community see how other open source project have their PR template choose good and add it to this project.

Sure. I will do my best.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609, thanks for your contribution.

No problem @Suraj-kumar00 . Thank you once again for giving me such an opportunity to work on a really amazing project.
