### ISSUE TITLE
Light mode and dar-mode not working and also further enhancement need 

### ISSUE THREAD

**Issue by alok-mishra143** [Suraj-kumar00/Flash-Fathom-AI#29]
#### **Summary**
This PR addresses the following issues:
- Fixes the non-functional light mode and dark mode toggle.
- Improves the overall user experience with visual enhancements and additional features.

#### **Changes Made**
1. **Fixed Light/Dark Mode Toggle:**
   - Corrected the logic for detecting the user’s theme preference and ensured smooth transitions between light and dark modes.
   - Updated the Tailwind CSS configuration to ensure proper theme application across the entire app.
   - Ensured all components correctly respond to the theme changes without visual glitches.

2. **Enhancements:**
   - **Improved Color Contrast:** Enhanced the contrast in both light and dark modes to improve readability.
   - **Animation Improvements:** Added smoother transitions for elements when toggling between light and dark modes.
   - **Mobile Responsiveness:** Ensured that the theme toggle works seamlessly on mobile devices.
   - **User Preferences:** Added functionality to save the user's theme preference locally, so it persists across sessions.

**Comment by Suraj-kumar00** [comment]
Hey @alok-mishra143 it yours!

Do remember you have 3 days to complete the issue!

And if you like the project please do consider to give the repo a star :star2:

**Comment by alok-mishra143** [comment]
@Suraj-kumar00 i had completed my task but when i clone the it doesn`t show any code just empty folder then i download the zip and set that project but not able to push the code any suggestion what wrong happeing

https://github.com/user-attachments/assets/95da2b9f-74f5-4fb2-8507-20ccb2697fe3

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 i had completed my task but when i clone the it doesn`t show any code just empty folder then i download the zip and set that project but not able to push the code any suggestion what wrong happeing i add the remote origin and also checkout to branch
> 
>  added.dark.mode.mp4

If you want we can connect over gmeet?

**Comment by alok-mishra143** [comment]
hey.alokmishra@gmail.com

**Comment by alok-mishra143** [comment]
![image](https://github.com/user-attachments/assets/284330be-cc64-4fc3-b0cc-baa2979a6a50)

**Comment by Suraj-kumar00** [comment]
> ![image](https://private-user-images.githubusercontent.com/100504874/378115031-284330be-cc64-4fc3-b0cc-baa2979a6a50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjQwODIsIm5iZiI6MTcyOTM2Mzc4MiwicGF0aCI6Ii8xMDA1MDQ4NzQvMzc4MTE1MDMxLTI4NDMzMGJlLWNjNjQtNGZjMy1iMGNjLWJhYTI5NzlhNmE1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxODQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTgzNDY2OTM1N2I1ZjZkNzA5MzQwY2NhZjdhMDJlMmQ4M2QzYzhjOTBkMzhkZTFhYTE5ZjZhZmY5Zjk1NGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WPCfbcIIT5277e9aXEEvIUKPDT7A7kIaQFnn0getwSo)

I just update can you please pull the changes!

**Comment by alok-mishra143** [comment]
The same error happened. Tomorrow, I will create the Notion document and send you what changes need to be made, so you can apply them directly :)

**Comment by Suraj-kumar00** [comment]
> The same error happened. Tomorrow, I will create the Notion document and send you what changes need to be made, so you can apply them directly :)

From my side i just again cross checked all folders now don't have any space after their names can you please try again?

**Comment by alok-mishra143** [comment]
yes now it solved

**Comment by Suraj-kumar00** [comment]
Hi @alok-mishra143, thanks for you contribution!

Can you see on the generate page this is not completely black! can you raise another pr by fixing this?

And if you like the project, can you please give the repo a star :star2: !

![image](https://github.com/user-attachments/assets/32a4b0d9-03b8-4755-9e7b-bef36d594381)

**Comment by alok-mishra143** [comment]
fixing that
