### ISSUE TITLE
Fixing Darkmode issue 

### ISSUE THREAD

**Issue by alok-mishra143** [Suraj-kumar00/Flash-Fathom-AI#33]
![image](https://github.com/user-attachments/assets/5aae1e59-30e0-4290-b232-7f643a174722)

fix user name display according to light mode and dark mode.
![image](https://github.com/user-attachments/assets/7661025f-95bc-4713-9fcc-594a0b597e49)

**Comment by Suraj-kumar00** [comment]
Hi @alok-mishra143 please look the navebar also because when i turn on dark mode the user's name is not showing in white color.

**Comment by Suraj-kumar00** [comment]
Thanks for you contribution @alok-mishra143 !
