### ISSUE TITLE
Improve the CONTRIBUTING.md file for the proper guide.

### ISSUE THREAD

**Issue by Suraj-kumar00** [Suraj-kumar00/Flash-Fathom-AI#4]
Give the complete step by step guide for the contributors to understand the project and can contribute by reading `CONTRIBUTING.md` file.

**Comment by subhamagarrwal** [comment]
could you kindly let me work on it.

**Comment by Suraj-kumar00** [comment]
Sure @subhamagarrwal, it's yours.
Please star ⭐ the repo of you found helpful.

**Comment by Suraj-kumar00** [comment]
Hi @subhamagarrwal, What is the update?

**Comment by subhamagarrwal** [comment]
will try to wrap up by tomorrow; sorry was very sick

**Comment by Suraj-kumar00** [comment]
> will try to wrap up by tomorrow; sorry am very sick

Oh get well soon!
Take your time I was just asking for update.

**Comment by Suraj-kumar00** [comment]
Hi @subhamagarrwal What's the update?

**Comment by subhamagarrwal** [comment]
ill make it by tomorrow and send a pr by tomorrow

**Comment by subhamagarrwal** [comment]
@Suraj-kumar00 i made a pr check once
