### ISSUE TITLE
[Doc] : Visual Enhancements , Fostering Contact Channel in README

### ISSUE THREAD

**Issue by Varunshiyam** [Suraj-kumar00/Flash-Fathom-AI#40]
**Is your feature request related to a problem? Please describe.**
#### Problem: A poorly structured or visually unappealing README can create confusion and hinder user engagement with a project.
----
This can lead to:

- **Difficulty understanding the project:** Newcomers may struggle to grasp

- **Reduced contributions:** Potential contributors may be deterred by a lack of clear information

- **Negative first impression:** An unprofessional README can reflect poorly on the project and discourage users from 
  exploring further.

---

**Describe the solution you'd like**

- To enhance communication and provide direct access to Project Guidance, I plan to include a dedicated Contact section 👤. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin⚡️ enabling contributors to readily connect with them and address any project-related queries. 

- Additionally, to improve readability and organization, I Planned to implement clear visual separations between each section of the contributor documentation, ensuring a user-friendly and easily navigable 🚏 experience. 

- Finally, to foster a welcoming 🙏🏻 and inclusive environment, I will incorporate personalized welcome messages for our Repository.

- To effectively convey the essence of our project and its objectives, I propose creating a customized cover image for the repository.

+ Kindly Assign me this Issue Under 🌸 Gssoc, ☘️ hacktoberfest . I'm grateful to work with Talented Crews ✨.

**Comment by Suraj-kumar00** [comment]
Hi @Varunshiyam, that's amazing!
I'll assing this issue to you but can you show me any sample of preview you have, so that I can also understand what visual enhancement you want to do.

**Comment by Suraj-kumar00** [comment]
And yeah if you like the project please do consider to give the repo a star :star2:

**Comment by Varunshiyam** [comment]
Welcome Greetings 💐

---

https://github.com/user-attachments/assets/bb68a4e5-0c90-4c60-9fb0-400fe9c78ea0

Documentation Seperation : 

----

<img width="713" alt="Screenshot 2024-10-21 at 10 39 17 AM" src="https://github.com/user-attachments/assets/18cf64eb-d01c-4e6a-87ba-bc31153384de">

Contact Section 👤: 

<img width="615" alt="Screenshot 2024-10-21 at 10 38 26 AM" src="https://github.com/user-attachments/assets/e136c535-3306-4fbf-8bdc-a7f6f172fbbf">

**Comment by Suraj-kumar00** [comment]
Hi @Varunshiyam, thanks for your interest but this repository don't need these things. you can work on any other issue.
