### ISSUE TITLE
Fix : The Dark Mode is Not Affecting the sign in & sign up page.

### ISSUE THREAD

**Issue by abishek1740P** [Suraj-kumar00/Flash-Fathom-AI#53]
**Describe the bug**
Dark Mode does not apply to the sign-in and sign-up pages. When toggling Dark Mode on other parts of the application, these pages remain in Light Mode, resulting in inconsistent theming across the application.

**To Reproduce**

**Expected behavior**
When Dark Mode is enabled, the sign-in and sign-up pages should automatically adopt Dark Mode styling, including changes to background colors, text colors, and other UI elements. This should make these pages visually consistent with the rest of the application, providing a seamless experience for users regardless of which page they are on.

**Screenshots**
![image](https://github.com/user-attachments/assets/d7b401f5-21d7-43e0-85df-e416857093b2)
![image](https://github.com/user-attachments/assets/82943f6e-646f-4159-a4f8-61790353c1d8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  - Chrome
 - Version - 22

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abishek1740P** [comment]
@Suraj-kumar00  Consider this under Hactoberfest-accepted  , gssoc , Hactoberfest

**Comment by Suraj-kumar00** [comment]
Hi @abishek1740P that's for rasing the issue, i have assigned you one issue please work on that and let's see if anyone else is interested in doing this issue otherwise it's yours

**Comment by zaheer-Khan3260** [comment]
Hey @Suraj-kumar00 i can fix this issue please assign it to me.

**Comment by Suraj-kumar00** [comment]
Hi @zaheer-Khan3260, I'm assigning this to you and you have 3 days to complete this issue.
And if you like the project please give the repo a star 🌟

**Comment by zaheer-Khan3260** [comment]
@Suraj-kumar00 This issue is fixed in PR #59. So, now you can close this Issue
