### ISSUE TITLE
The output of generate flashcard is not responsive

### ISSUE THREAD

**Issue by Suraj-kumar00** [Suraj-kumar00/Flash-Fathom-AI#61]
**Describe the bug**
The output of generate flashcard is not responsive

**To Reproduce**
1. Go to 'Generate Flashcard'
2. Click on 'Generare flashcard' after entering your input
3. The generated output will be outside the box size is you click on circle left side.

**Expected behavior**
The generated flashcard should be responsive

**Screenshots**
![Screenshot_20241027_150146_Chrome](https://github.com/user-attachments/assets/d6b8c7d8-2677-48d6-adb5-eeaf1f32c3ef)
![Screenshot_20241027_150153_Chrome](https://github.com/user-attachments/assets/17b2b824-5cf5-4d0c-b3e8-faf573fbc641)

**Smartphone (please complete the following information):**
 - Device: [Samsung s23]
 - OS: [Android 14]
 - Browser [Chrome browser]

**Comment by haseebzaki-07** [comment]
hey @Suraj-kumar00 please assign me this issue

**Comment by Suraj-kumar00** [comment]
Hi @haseebzaki-07, if you have read the contributing.md file there i have mentioned how to self assing.

**Comment by haseebzaki-07** [comment]
.take
