### ISSUE TITLE
Add "Back to Top" Scroll Button in README

### ISSUE THREAD

**Issue by T-Fathima** [Suraj-kumar00/Flash-Fathom-AI#65]
**Is your feature request related to a problem? Please describe.**
Currently, the README file does not include a "Back to Top" button, making it difficult for users to navigate back to the beginning after scrolling through lengthy sections. Adding a "Back to Top" link at the end of readme file will improve navigation, providing a better user experience for readers.

**Describe the solution you'd like**
Insert a "Back to Top" link or button at the end of readme file to allow users to quickly return to the top of the README.

**Additional context**
@Suraj-kumar00 I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by Suraj-kumar00** [comment]
Hi @T-Fathima, thanks for raising the issue but it's not required for this repo. Hopw you understand.
