### ISSUE TITLE
Update README for Enhanced Appeal and Contributor Section

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Suraj-kumar00/Flash-Fathom-AI#7]
Propose to enhance the README file by making it more engaging and visually appealing. Additionally, include a contributor section similar to the one in the provided image to acknowledge the contributors effectively.

![image](https://github.com/user-attachments/assets/4b880b60-984d-48d3-81b6-99adb9fa2144)

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, go for it and please include the proper git commit message and when you open the PR do include the screenshot of the preview.

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, What is the update on the issue?
Have you completed or are you facing any issue?

**Comment by AnushkaChouhan25** [comment]
> Hi @AnushkaChouhan25, What is the update on the issue? Have you completed or are you facing any issue?

Done 👍

**Comment by Suraj-kumar00** [comment]
> > Hi @AnushkaChouhan25, What is the update on the issue? Have you completed or are you facing any issue?
> 
> Done 👍

Requested changes please check them!
