### ISSUE TITLE
feat: add motion animations to whole page

### ISSUE THREAD

**Issue by AE-Hertz** [Suraj-kumar00/Flash-Fathom-AI#71]
I will add motion animations to the whole homepage.
This will enhance the UI drastically.

Deps using -
Framer motion.

Assign me this under hacktoberfest and gssoc-ext, i expect a level 3 for this.

@Suraj-kumar00 assign me this issue asap.

**Comment by Suraj-kumar00** [comment]
Hi @AE-Hertz it's yours, you have 3 days to complete this issue.
If you like the project do consider to give the repo a star :star2:
