### ISSUE TITLE
I want to add a scroll to top button in every page

### ISSUE THREAD

**Issue by souvikpramanikgit** [Suraj-kumar00/Flash-Fathom-AI#78]
**Is your feature request related to a problem? Please describe.**

I want to add a scroll to top option in every page

**Additional context**

**Comment by souvikpramanikgit** [comment]
Assign @Suraj-kumar00

**Comment by Suraj-kumar00** [comment]
Hi @souvikpramanikgit, I don't need this feature as of now. Can you please work on any other issue!
