### ISSUE TITLE
Want to add newsletter in the bottom of the page

### ISSUE THREAD

**Issue by souvikpramanikgit** [Suraj-kumar00/Flash-Fathom-AI#79]
Want to add newsletter in the bottom of the page instead of the footer, like instead of this
![image](https://github.com/user-attachments/assets/97f4a94b-2a91-4d1a-b4a8-61cb36588413)

i want to implement this

![image](https://github.com/user-attachments/assets/647fc4a0-cfe3-43a6-a4ad-5ad489b96788)

**Comment by Suraj-kumar00** [comment]
Hi @souvikpramanikgit Not planned for this one as of now.
