### ISSUE TITLE
Want to add a new section in main page

### ISSUE THREAD

**Issue by souvikpramanikgit** [Suraj-kumar00/Flash-Fathom-AI#80]
**Is your feature request related to a problem? Please describe.**

Want to add a new section in main page
![image](https://github.com/user-attachments/assets/a19e7a20-e0cb-4336-a8e9-b3c99a016d37)

**Additional context**

**Comment by Suraj-kumar00** [comment]
Hi @souvikpramanikgit, not planned for the new ui for now
