### ISSUE TITLE
Heading Color Visibility and Navbar Enhancement

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Suraj-kumar00/Flash-Fathom-AI#9]
The heading color is currently set to white, which renders it invisible against the white background. This makes it difficult for users to read the headings on the page.

![image](https://github.com/user-attachments/assets/3152646f-0183-4124-bb5c-52fb3f8523c3)

*Expected Outcome* : 
- Heading Color Change:

Change the heading color to a darker shade (e.g., black or dark gray) to ensure visibility against the white background.
Ensure that the updated color scheme is consistent with the overall design and theme of the website.

- Navbar Enhancement:

Improve the navbar design to enhance usability and aesthetics.
Ensure that the navbar items are clearly visible and accessible, possibly by adjusting font size, color, or adding hover effects.
Consider adding a background color or shadow to the navbar to differentiate it from the content below.

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, thanks for raising the issue but can you please look at the issue #1 it's about implementing the dark theme all over the project the toggle is added just you have to implement the so that when user choose dark theme it should me dark.
If you wish to work on this issue you work on the issue #1. Let me know if you want to do!

**Comment by AnushkaChouhan25** [comment]
Hello @Suraj-kumar00 , Okay you assign me issue #1 and also I can do small enhancement on the navbar.

**Comment by Suraj-kumar00** [comment]
> Reference in new issue

Okay but do remember open the PR separately of the previous issue and this #1  issue okay. And please Include the preview of your changes like screenshot.

**Comment by Suraj-kumar00** [comment]
> Hello @Suraj-kumar00 , Okay you assign me issue #1 and also I can do small enhancement on the navbar.

Just comment `.take` on the issue and it'll assigned to you.

**Comment by AnushkaChouhan25** [comment]
.take

**Comment by Suraj-kumar00** [comment]
Hi @AnushkaChouhan25, how you been?
What the update on the issue?
